/**
 * Generates `dist/_redirects` after the Vite build.
 *
 * Two rules, and the order between them is the whole point:
 *
 *   /api/*  ->  <API_PROXY_TARGET>/api/:splat   200  (proxied to the backend)
 *   /*      ->  /index.html                     200  (SPA fallback)
 *
 * Netlify evaluates `_redirects` top to bottom and stops at the first match, so
 * the API rule must precede the catch-all. Reversed, every API call would be
 * answered with the HTML shell and the portal would fail with parse errors
 * rather than anything that names the real cause.
 *
 * Proxying rather than calling the backend cross-origin is what preserves the
 * security model: the browser sees one origin, so the session cookie stays
 * SameSite=Strict and the frontend keeps `credentials: "same-origin"`. Nothing
 * in `apps/web` needs to know the backend's address, and no CORS is involved.
 *
 * The target is an environment variable rather than a literal because
 * `netlify.toml` cannot interpolate one into a redirect rule. It is a public
 * URL, not a secret.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDir = path.join(projectRoot, "dist");

const SPA_FALLBACK = "/*    /index.html    200";

function resolveTarget() {
  const raw = process.env.API_PROXY_TARGET;
  if (raw === undefined || raw.trim() === "") {
    return undefined;
  }

  let parsed;
  try {
    parsed = new URL(raw.trim());
  } catch {
    throw new Error(`API_PROXY_TARGET is not a valid URL: ${raw}`);
  }

  if (parsed.protocol !== "https:" && parsed.hostname !== "localhost") {
    throw new Error(
      `API_PROXY_TARGET must use https (got ${parsed.protocol}//). The session cookie is ` +
        "Secure in production and would be dropped over plain http.",
    );
  }

  if (parsed.pathname !== "/") {
    throw new Error(
      `API_PROXY_TARGET must be an origin with no path (got ${parsed.pathname}). ` +
        "The /api prefix is added by the redirect rule.",
    );
  }

  return parsed.origin;
}

const target = resolveTarget();

// On Netlify a missing target is a broken deploy, not a local build: every API
// call would fall through to the SPA rule and return HTML. Fail the build.
if (target === undefined && process.env.NETLIFY === "true") {
  console.error(
    "API_PROXY_TARGET is not set.\n" +
      "Set it in the Netlify site's environment variables to the backend's origin, " +
      "for example https://procureai-api.onrender.com, and redeploy.",
  );
  process.exit(1);
}

const rules =
  target === undefined
    ? ["# No API_PROXY_TARGET set at build time: SPA fallback only.", SPA_FALLBACK]
    : [`/api/*    ${target}/api/:splat    200`, SPA_FALLBACK];

const contents = [
  "# Generated by scripts/writeRedirects.mjs. Do not edit by hand.",
  "# Order matters: the first matching rule wins.",
  "",
  ...rules,
  "",
].join("\n");

await mkdir(outputDir, { recursive: true });
await writeFile(path.join(outputDir, "_redirects"), contents, "utf8");

console.log(
  target === undefined
    ? "Wrote dist/_redirects with the SPA fallback only (no API_PROXY_TARGET set)."
    : `Wrote dist/_redirects proxying /api/* to ${target}`,
);
